version: '3.5'

services:
    web:
        container_name: ${PROJECT_NAME}_web
        image: nginx:latest
        ports:
            - "$WEB_PORT:80" # auto - please leave this "auto" in comment.
        volumes:
            - ..:/code
            - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    php_fpm:
        container_name: ${PROJECT_NAME}_fpm
        build:
            context: fpm
            dockerfile: Dockerfile
        volumes:
            - ..:/code
    phpmyadmin:
        container_name: ${PROJECT_NAME}_pma
        build:
            context: pma
            dockerfile: Dockerfile
        ports:
            - "$PROTECTED_PMA_PORT:80"

networks:
    ${PROJECT_NAME}-network:
        name: ${PROJECT_NAME}-network